name: Express.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  test:
    runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: johnpeter83
            POSTGRES_DB: pruebas_peter
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
              - 5432:5432